#Defining the deployment for nginx pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-deploy
  labels:
    app: my-app
spec:
  template:
    metadata:
       name: my-first-pod
       labels:
         name: my-pod
    spec:
      containers:
        -  name: my-first-container
           image: rakesh09867/my-app:${IMAGE_TAG}
           ports:
           - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      name: my-pod
